nav:
  - Home:
    - Welcome to my notebook ~: index.md
    - Friends: friends.md
  - DS/Algo.:
    - Fundamentals of Data Structures:
      - Fundamentals of Data Structures: ZJU-Fundamentals of Data Structures/index.md
      - Ch.02 Algorithm Analysis: ZJU-Fundamentals of Data Structures/Ch.02 Algorithm Analysis.md
      - Ch.03 List: ZJU-Fundamentals of Data Structures/Ch.03 List.md
      - Ch.04 Trees: ZJU-Fundamentals of Data Structures/Ch.04 Trees.md
      - Ch.05 Priority Queues (Heaps): ZJU-Fundamentals of Data Structures/Ch.05 Priority Queues (Heaps).md
      - Ch.06 Sorting: ZJU-Fundamentals of Data Structures/Ch.06 Sorting.md
      - Ch.07 Hashing: ZJU-Fundamentals of Data Structures/Ch.07 Hashing.md
      - Ch.08 Disjoint Set: ZJU-Fundamentals of Data Structures/Ch.08 Disjoint Set.md
      - Ch.09 Graph Algorithms: ZJU-Fundamentals of Data Structures/Ch.09 Graph Algorithms.md
      - Cheat Sheet: ZJU-Fundamentals of Data Structures/Cheat Sheet.md
    - Advanced Data Structure & Algorithm Analysis:
      - Advanced Data Structure & Algorithm Analysis: ZJU-Advanced Data Structure & Algorithm Analysis/index.md
      - 01 AVL Trees, Splay Trees and Amortized Analysis: ZJU-Advanced Data Structure & Algorithm Analysis/ADS 01 AVL Trees, Splay Trees and Amortized Analysis.md
      - 02 Red-Black Trees and B+ Trees: ZJU-Advanced Data Structure & Algorithm Analysis/ADS 02 Red-Black Trees and B+ Trees.md
      - 03 Inverted File Index: ZJU-Advanced Data Structure & Algorithm Analysis/ADS 03 Inverted File Index.md
      - 04 Leftistf Heaps and Skew Heaps: ZJU-Advanced Data Structure & Algorithm Analysis/ADS 04 Leftist Heaps and Skew Heaps.md
      - 05 Binomial Queue: ZJU-Advanced Data Structure & Algorithm Analysis/ADS 05 Binomial Queue.md
      - 06 Backtracking: ZJU-Advanced Data Structure & Algorithm Analysis/ADS 06 Backtracking.md
      - 07 Divide and Conquer: ZJU-Advanced Data Structure & Algorithm Analysis/ADS 07 Divide and Conquer.md
      - 08 Dynamic Programming: ZJU-Advanced Data Structure & Algorithm Analysis/ADS 08 Dynamic Programming.md
      - 09 Greedy Algorithm: ZJU-Advanced Data Structure & Algorithm Analysis/ADS 09 Greedy Algorithm.md
      - 10 NP-Completeness: ZJU-Advanced Data Structure & Algorithm Analysis/ADS 10 NP-Completeness.md
      - 11 Approximation: ZJU-Advanced Data Structure & Algorithm Analysis/ADS 11 Approximation.md
      - 12 Local Search: ZJU-Advanced Data Structure & Algorithm Analysis/ADS 12 Local Search.md
      - 13 Randomized Algorithms: ZJU-Advanced Data Structure & Algorithm Analysis/ADS 13 Randomized Algorithms.md
      - 14 Parallel Algorithms: ZJU-Advanced Data Structure & Algorithm Analysis/ADS 14 Parallel Algorithms.md
      - 15 External Sorting: ZJU-Advanced Data Structure & Algorithm Analysis/ADS 15 External Sorting.md
      - Final Cheat Sheet: ZJU-Advanced Data Structure & Algorithm Analysis/ADS Cheat Sheet.md
      - Final DP: ZJU-Advanced Data Structure & Algorithm Analysis/ADS Cheat Sheet Dynamic Programming.md
      - Final Questions: ZJU-Advanced Data Structure & Algorithm Analysis/ADS Final Questions.md
  - Coding/Lang.:
    - 汇编语言程序设计基础:
      - 汇编语言程序设计基础: ZJU-Assembly Fundamentals/index.md
      - 01 数据类型和变量: ZJU-Assembly Fundamentals/ASMF 01 数据类型和变量.md
      - 02 汇编语言源程序格式: ZJU-Assembly Fundamentals/ASMF 02 汇编语言源程序格式.md
      - 03 内存与寻址: ZJU-Assembly Fundamentals/ASMF 03 内存与寻址.md
      - 04 寄存器: ZJU-Assembly Fundamentals/ASMF 04 寄存器.md
      - 05 段和堆栈: ZJU-Assembly Fundamentals/ASMF 05 段和堆栈.md
      - 06 中断和函数调用: ZJU-Assembly Fundamentals/ASMF 06 中断和函数调用.md
      - 07 数据传送指令: ZJU-Assembly Fundamentals/ASMF 07 数据传送指令.md
      - 08 转换指令: ZJU-Assembly Fundamentals/ASMF 08 转换指令.md
      - 09 算术运算指令: ZJU-Assembly Fundamentals/ASMF 09 算术运算指令.md
      - 10 逻辑运算和移位指令: ZJU-Assembly Fundamentals/ASMF 10 逻辑运算和移位指令.md
      - 11 字符串操作指令: ZJU-Assembly Fundamentals/ASMF 11 字符串操作指令.md
      - 12 控制转移指令: ZJU-Assembly Fundamentals/ASMF 12 控制转移指令.md
      - Cheat Sheet: ZJU-Assembly Fundamentals/ASMF Cheat Sheet.md
  - Others:
    - GAMES101:
      - GAMES101: GAMES101/index.md
      - 01 Introduction: GAMES101/GAMES101 01 Introduction.md
      - 02 About Linear Algebra: GAMES101/GAMES101 02 A Swift and Brutal Introduction to Linear Algebra.md
      - 03 Transformation: GAMES101/GAMES101 03 Transformation.md
      - 04 Resterization: GAMES101/GAMES101 04 Rasterization.md
      - 05 Shading: GAMES101/GAMES101 05 Shading.md
      - 06 Geometry: GAMES101/GAMES101 06 Geometry.md
      - 07 Ray Tracing: GAMES101/GAMES101 07 Ray Tracing.md
      - 08 Materials and Appearances: GAMES101/GAMES101 08 Materials and Appearances.md
      - 09 Advanced Topics in Rendering: GAMES101/GAMES101 09 Advanced Topics in Rendering.md
      - 10 Cameras, Lenses and Light Fields: GAMES101/GAMES101 10 Cameras, Lenses and Light Fields.md
      - 11 Color and Perception: GAMES101/GAMES101 11 Color and Perception.md
      - 12 Animation: GAMES101/GAMES101 12 Animation.md
    - HPC101:
      - HPC101: ZJU-HPC101/index.md
      - Lec.02 体系结构与高性能计算基础: ZJU-HPC101/Lec.02 体系结构与高性能计算基础.md
      - Lec.03 高性能计算方法学: ZJU-HPC101/Lec.03 高性能计算方法学.md
      - Lec.04 集群软硬件及运维基础: ZJU-HPC101/Lec.04 集群软硬件及运维基础.md
      - Lec.05 向量化计算: ZJU-HPC101/Lec.05 向量化计算.md
      - Lec.06 CUDA C 编程基础: ZJU-HPC101/Lec.06 CUDA C 编程基础.md
      - Lec.07 OpenMP, MPI 并行计算基础: ZJU-HPC101/Lec.07 OpenMP, MPI 并行计算基础.md
      - Lec.09 Introduction to Machine Learning: ZJU-HPC101/Lec.09 Introduction to Machine Learning.md
    


# site metadata
site_name: Emergent Space
site_author: Emergent Twilight
site_url: https://emergenttwilight.github.io/emergent-space/
site_description: Emergent Space
use_directory_urls: false
repo_url: https://github.com/EmergentTwilight/emergent-space/
repo_name: emergent-space
# copyright: Copyright &copy; 2025 [EmergentTwilight](https://github.com/EmergentTwilight)
copyright: Copyright &copy; 2024-2025 <a href="https://github.com/EmergentTwilight">EmergentTwilight</a>
site_dir: "site"

theme:
  favicon: __srcs/images/logo-E.png
  logo: __srcs/images/logo-gaussian-small.png
  name: material
  custom_dir: overrides
  language: en
  features:
    - content.action.edit # 编辑按钮
    - content.action.view # 源码按钮
    - content.code.copy # 代码块复制按钮
    # - content.code.annotate  # 代码块中点击展开的注释，见 https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations

    # Setting up navigation
    # - navigation.instant  # 无论目标页面是否加载完毕，都会立即跳转，在页面内容较多时增强体验（必须配置 site_url）
    # - navigation.instant.progress  # 若页面加载时间超过 400ms，会在页面顶端显示进度
    - navigation.tracking # 地址中会包括锚点（标题）
    - navigation.tabs # 一级目录出现在顶栏
    # - navigation.tabs.sticky  # 顶栏固定，不会在 scroll down 时隐藏
    # - navigation.sections  # 二级目录在左栏中以 section 形式出现
    # - navigation.expand  # 左栏目录默认展开
    - navigation.prune # only the visible navigation items are included in the rendered HTML，有利于加速
    - navigation.indexes # 目录名指向 index.md，需要类似这样写 nav: - Section: - section/index.md  - Page 1: section/page-1.md
    - navigation.top # 回到顶部按钮
    - navigation.footer # 底部的上下页按钮

    # - header.autohide  # 下滑时隐藏 header

    # - toc.follow  # 右侧目录跟随滚动，保持当前锚点对应标题可见
    # - toc.integrate  # 右栏和左栏合并

    # Setting up site search
    - search.suggest # 好像没用？
    - search.highlight # 搜索结果高亮
    - search.share # 分享按钮，分享当前搜索

  palette: # 配色方案
    - media: "(prefers-color-scheme)" # 跟随系统
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" # 亮色主题
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 暗色主题
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to system preference

  font:
    # text: Noto Serif SC
    code: Roboto Mono

  # custom_dir: __srcs/custom  # https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/

markdown_extensions:
  # python markdown
  - toc:
      permalink: "#"
      permalink_title: Locate to heading
      toc_depth: 4
      baselevel: 2
      slugify: !!python/name:markdown.extensions.toc.slugify_unicode
  - admonition # callouts
  # - attr-list  # 允许为 md 元素添加 html 属性，例如 grid
  - def_list # 允许使用定义列表，见 https://squidfunk.github.io/mkdocs-material/reference/lists/#using-definition-lists
  - footnotes # 脚注
  - md_in_html # 允许在 html 中使用 markdown

  # pymdownx extensions
  - pymdownx.details # 可折叠的 callouts
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem # better emphasis
  - pymdownx.blocks.caption
  # - pymdownx.caret  # H^2^O 上标
  - pymdownx.mark # ==highlight==
  - pymdownx.tilde # ~~strikethrough~~，CH~3~CH~2~OH 下标
  # - pymdownx.critic  # > comment
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true # 行号链接
      linenums: true # 行号
      pygments_lang_class: true # This option instructs Pygments to add a CSS class to identify the language of the code block, which is essential for custom annotation markers to function
      use_pygments: true
      # auto_title: true  # 如果没有 title，则以语言名作为 title
      line_spans: __span # 行高亮需要使用 span 标签
  - pymdownx.inlinehilite # 行内代码高亮，`:::lang code`
  # - pymdownx.keys  # 方便渲染按键图标
  - pymdownx.smartsymbols # https://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/，用处不大
  # - pymdownx.snippets  # -8<- "filename.ext" https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
  - pymdownx.tabbed # === "tab 1"  === "tab 2"
  - pymdownx.tasklist: # - [ ]
      custom_checkbox: true

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css # $latex$
  - __srcs/css/banner.css # page banner
  - __srcs/css/sidebar.css
  - __srcs/css/content.css # main md content
  - __srcs/css/custom.css # other
  - __srcs/css/font.css
  - __srcs/css/list_callouts.css
  - __srcs/css/friend_link.css

extra_javascript:
  # $latex$
  - __srcs/javascript/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - __srcs/javascript/toc.js

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/EmergentTwilight
    - icon: fontawesome/regular/envelope
      link: mailto:emergentshores@outlook.com

plugins:
  - search
  - callouts # obsidian-like callouts
  - emergent_space_wikilink_converter
  - emergent_space_implicit_md_links
  - emergent_space_code_block_hl_formatter
  - emergent_space_list_callouts:
      symbol_map:
        '&': 'highlight'
        '?': 'question'
        '!': 'warning'
        '~': 'bookmark'
        '@': 'tip'
        '$': 'success'
        '%': 'quote'
  # - toc
  # - statistics
